/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PhantomRiskV1Interface extends ethers.utils.Interface {
  functions: {
    "attack(uint8,uint8,uint256,bool)": FunctionFragment;
    "claimFees()": FunctionFragment;
    "claimPleb(uint8,uint256,address)": FunctionFragment;
    "claimTicketRevenue()": FunctionFragment;
    "claimableFees(address)": FunctionFragment;
    "createRegions(uint8[],uint8[],uint8[],uint8[][],uint8[],uint256[],uint8[],uint256[])": FunctionFragment;
    "deployGarrison(uint8,uint8,uint256,bool)": FunctionFragment;
    "deployWorker(uint8,uint256)": FunctionFragment;
    "deploymentDone()": FunctionFragment;
    "factionDead(uint256)": FunctionFragment;
    "getClaimablePleb(uint8,address)": FunctionFragment;
    "getProductionByLord(uint8,address)": FunctionFragment;
    "getRegion(uint8)": FunctionFragment;
    "getRegionIds()": FunctionFragment;
    "getRegionTiers()": FunctionFragment;
    "getSiege(uint8)": FunctionFragment;
    "isNeighbor(uint8,uint8)": FunctionFragment;
    "joinGame()": FunctionFragment;
    "layout()": FunctionFragment;
    "owner()": FunctionFragment;
    "player(address)": FunctionFragment;
    "pleb()": FunctionFragment;
    "regionAllowsAttack(uint8,uint8)": FunctionFragment;
    "regionIds(uint256)": FunctionFragment;
    "regionTiers(uint256)": FunctionFragment;
    "regions(uint8)": FunctionFragment;
    "regionsPerFaction(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "resolveSiege(uint8)": FunctionFragment;
    "setDeploymentDone(uint8,uint8)": FunctionFragment;
    "setRegionTiers(tuple[5])": FunctionFragment;
    "setSettings(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "settings()": FunctionFragment;
    "siegeOutcome(uint8)": FunctionFragment;
    "ticketRevenueRecipient()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "attack",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "claimFees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimPleb",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTicketRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableFees",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createRegions",
    values: [
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[][],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployGarrison",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWorker",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentDone",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "factionDead",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimablePleb",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductionByLord",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegionIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegionTiers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSiege",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isNeighbor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "joinGame", values?: undefined): string;
  encodeFunctionData(functionFragment: "layout", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "player", values: [string]): string;
  encodeFunctionData(functionFragment: "pleb", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "regionAllowsAttack",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regionIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regionTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regionsPerFaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveSiege",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDeploymentDone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegionTiers",
    values: [
      [
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        }
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettings",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "settings", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "siegeOutcome",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketRevenueRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimPleb", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimTicketRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRegions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployGarrison",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentDone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "factionDead",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimablePleb",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductionByLord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRegion", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRegionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegionTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSiege", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isNeighbor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "layout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "player", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pleb", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regionAllowsAttack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "regionIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regionTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "regions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regionsPerFaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveSiege",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDeploymentDone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegionTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "siegeOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketRevenueRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Attacked(address,uint8,uint8,uint256)": EventFragment;
    "ClaimedPleb(address,uint256)": EventFragment;
    "DeployedGarrison(address,uint8,uint256)": EventFragment;
    "DeployedWorker(address,uint8,uint256)": EventFragment;
    "DeploymentDone()": EventFragment;
    "FactionLost(uint8)": EventFragment;
    "FeesClaimed(address,uint256)": EventFragment;
    "JoinedGame(address,uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RegionTierIncreased(uint8,uint8)": EventFragment;
    "ResolvedSiege(uint8,uint8,uint256,uint8,uint256,bool)": EventFragment;
    "SettingsChanged(tuple,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Attacked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimedPleb"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployedGarrison"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployedWorker"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeploymentDone"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FactionLost"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeesClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JoinedGame"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegionTierIncreased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ResolvedSiege"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SettingsChanged"): EventFragment;
}

export type AttackedEvent = TypedEvent<
  [string, number, number, BigNumber] & {
    player: string;
    faction: number;
    region: number;
    soldier: BigNumber;
  }
>;

export type ClaimedPlebEvent = TypedEvent<
  [string, BigNumber] & { player: string; pleb: BigNumber }
>;

export type DeployedGarrisonEvent = TypedEvent<
  [string, number, BigNumber] & {
    player: string;
    region: number;
    soldier: BigNumber;
  }
>;

export type DeployedWorkerEvent = TypedEvent<
  [string, number, BigNumber] & {
    player: string;
    region: number;
    worker: BigNumber;
  }
>;

export type DeploymentDoneEvent = TypedEvent<[] & {}>;

export type FactionLostEvent = TypedEvent<[number] & { faction: number }>;

export type FeesClaimedEvent = TypedEvent<
  [string, BigNumber] & { account: string; amount: BigNumber }
>;

export type JoinedGameEvent = TypedEvent<
  [string, number] & { player: string; faction: number }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type RegionTierIncreasedEvent = TypedEvent<
  [number, number] & { region: number; tier: number }
>;

export type ResolvedSiegeEvent = TypedEvent<
  [number, number, BigNumber, number, BigNumber, boolean] & {
    region: number;
    defender: number;
    defendingSoldier: BigNumber;
    attacker: number;
    attackingSoldier: BigNumber;
    defenderWon: boolean;
  }
>;

export type SettingsChangedEvent = TypedEvent<
  [
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      ticketPrice: BigNumber;
      rallyTime: BigNumber;
      siegeTime: BigNumber;
      siegeCooldown: BigNumber;
      overwhelming: BigNumber;
      overwhelmingPenalty: BigNumber;
      plebForSoldier: BigNumber;
      plebForWorker: BigNumber;
    },
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      ticketPrice: BigNumber;
      rallyTime: BigNumber;
      siegeTime: BigNumber;
      siegeCooldown: BigNumber;
      overwhelming: BigNumber;
      overwhelmingPenalty: BigNumber;
      plebForSoldier: BigNumber;
      plebForWorker: BigNumber;
    }
  ] & {
    oldSettings: [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      ticketPrice: BigNumber;
      rallyTime: BigNumber;
      siegeTime: BigNumber;
      siegeCooldown: BigNumber;
      overwhelming: BigNumber;
      overwhelmingPenalty: BigNumber;
      plebForSoldier: BigNumber;
      plebForWorker: BigNumber;
    };
    newSettings: [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      ticketPrice: BigNumber;
      rallyTime: BigNumber;
      siegeTime: BigNumber;
      siegeCooldown: BigNumber;
      overwhelming: BigNumber;
      overwhelmingPenalty: BigNumber;
      plebForSoldier: BigNumber;
      plebForWorker: BigNumber;
    };
  }
>;

export class PhantomRiskV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PhantomRiskV1Interface;

  functions: {
    attack(
      regionTo: BigNumberish,
      regionFrom: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimFees(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimPleb(
      _region: BigNumberish,
      _frontendFee: BigNumberish,
      _frontendProvider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTicketRevenue(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimableFees(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createRegions(
      _regionId: BigNumberish[],
      _column: BigNumberish[],
      _row: BigNumberish[],
      _neighbors: BigNumberish[][],
      _tier: BigNumberish[],
      _garrison: BigNumberish[],
      _controlledBy: BigNumberish[],
      _cantGetAttackedTill: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployGarrison(
      regionTo: BigNumberish,
      neighborRegion: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployWorker(
      regionTo: BigNumberish,
      workerAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deploymentDone(overrides?: CallOverrides): Promise<[boolean]>;

    factionDead(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getClaimablePleb(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getProductionByLord(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getRegion(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number[],
        number,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber
      ] & {
        id_: number;
        column_: number;
        row_: number;
        neighbors_: number[];
        tier_: number;
        garrison_: BigNumber;
        totalWorker_: BigNumber;
        controlledBy_: number;
        besieged_: boolean;
        cantGetAttackedTill_: BigNumber;
      }
    >;

    getRegionIds(overrides?: CallOverrides): Promise<[number[]]>;

    getRegionTiers(
      overrides?: CallOverrides
    ): Promise<
      [
        [
          [BigNumber, BigNumber, BigNumber] & {
            workerLimit: BigNumber;
            requiredGarrison: BigNumber;
            plebPerSec: BigNumber;
          },
          [BigNumber, BigNumber, BigNumber] & {
            workerLimit: BigNumber;
            requiredGarrison: BigNumber;
            plebPerSec: BigNumber;
          },
          [BigNumber, BigNumber, BigNumber] & {
            workerLimit: BigNumber;
            requiredGarrison: BigNumber;
            plebPerSec: BigNumber;
          },
          [BigNumber, BigNumber, BigNumber] & {
            workerLimit: BigNumber;
            requiredGarrison: BigNumber;
            plebPerSec: BigNumber;
          },
          [BigNumber, BigNumber, BigNumber] & {
            workerLimit: BigNumber;
            requiredGarrison: BigNumber;
            plebPerSec: BigNumber;
          }
        ]
      ]
    >;

    getSiege(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber] & {
        attacker_: number;
        attackedAt_: BigNumber;
        soldier_: BigNumber;
      }
    >;

    isNeighbor(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    joinGame(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    layout(
      overrides?: CallOverrides
    ): Promise<[number, number] & { rows: number; columns: number }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    player(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[number, boolean] & { faction: number; joined: boolean }>;

    pleb(overrides?: CallOverrides): Promise<[string]>;

    regionAllowsAttack(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    regionIds(arg0: BigNumberish, overrides?: CallOverrides): Promise<[number]>;

    regionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        workerLimit: BigNumber;
        requiredGarrison: BigNumber;
        plebPerSec: BigNumber;
      }
    >;

    regions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber,
        [number, BigNumber, BigNumber] & {
          attacker: number;
          attackedAt: BigNumber;
          soldier: BigNumber;
        }
      ] & {
        id: number;
        column: number;
        row: number;
        tier: number;
        garrison: BigNumber;
        totalWorker: BigNumber;
        controlledBy: number;
        besieged: boolean;
        cantGetAttackedTill: BigNumber;
        siege: [number, BigNumber, BigNumber] & {
          attacker: number;
          attackedAt: BigNumber;
          soldier: BigNumber;
        };
      }
    >;

    regionsPerFaction(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resolveSiege(
      _region: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDeploymentDone(
      _rows: BigNumberish,
      _columns: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRegionTiers(
      tiers: [
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        }
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSettings(
      _ticketPrice: BigNumberish,
      _rallyTime: BigNumberish,
      _siegeTime: BigNumberish,
      _siegeCooldown: BigNumberish,
      _overwhelming: BigNumberish,
      _overwhelmingPenalty: BigNumberish,
      _plebForSoldier: BigNumberish,
      _plebForWorker: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settings(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        ticketPrice: BigNumber;
        rallyTime: BigNumber;
        siegeTime: BigNumber;
        siegeCooldown: BigNumber;
        overwhelming: BigNumber;
        overwhelmingPenalty: BigNumber;
        plebForSoldier: BigNumber;
        plebForWorker: BigNumber;
      }
    >;

    siegeOutcome(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean, BigNumber]>;

    ticketRevenueRecipient(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  attack(
    regionTo: BigNumberish,
    regionFrom: BigNumberish,
    soldierAmount: BigNumberish,
    resolvesSiege: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimFees(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimPleb(
    _region: BigNumberish,
    _frontendFee: BigNumberish,
    _frontendProvider: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTicketRevenue(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimableFees(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  createRegions(
    _regionId: BigNumberish[],
    _column: BigNumberish[],
    _row: BigNumberish[],
    _neighbors: BigNumberish[][],
    _tier: BigNumberish[],
    _garrison: BigNumberish[],
    _controlledBy: BigNumberish[],
    _cantGetAttackedTill: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployGarrison(
    regionTo: BigNumberish,
    neighborRegion: BigNumberish,
    soldierAmount: BigNumberish,
    resolvesSiege: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployWorker(
    regionTo: BigNumberish,
    workerAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deploymentDone(overrides?: CallOverrides): Promise<boolean>;

  factionDead(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  getClaimablePleb(
    _region: BigNumberish,
    _player: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getProductionByLord(
    _region: BigNumberish,
    _player: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  getRegion(
    _region: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      number,
      number,
      number[],
      number,
      BigNumber,
      BigNumber,
      number,
      boolean,
      BigNumber
    ] & {
      id_: number;
      column_: number;
      row_: number;
      neighbors_: number[];
      tier_: number;
      garrison_: BigNumber;
      totalWorker_: BigNumber;
      controlledBy_: number;
      besieged_: boolean;
      cantGetAttackedTill_: BigNumber;
    }
  >;

  getRegionIds(overrides?: CallOverrides): Promise<number[]>;

  getRegionTiers(
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber, BigNumber, BigNumber] & {
        workerLimit: BigNumber;
        requiredGarrison: BigNumber;
        plebPerSec: BigNumber;
      },
      [BigNumber, BigNumber, BigNumber] & {
        workerLimit: BigNumber;
        requiredGarrison: BigNumber;
        plebPerSec: BigNumber;
      },
      [BigNumber, BigNumber, BigNumber] & {
        workerLimit: BigNumber;
        requiredGarrison: BigNumber;
        plebPerSec: BigNumber;
      },
      [BigNumber, BigNumber, BigNumber] & {
        workerLimit: BigNumber;
        requiredGarrison: BigNumber;
        plebPerSec: BigNumber;
      },
      [BigNumber, BigNumber, BigNumber] & {
        workerLimit: BigNumber;
        requiredGarrison: BigNumber;
        plebPerSec: BigNumber;
      }
    ]
  >;

  getSiege(
    _region: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber] & {
      attacker_: number;
      attackedAt_: BigNumber;
      soldier_: BigNumber;
    }
  >;

  isNeighbor(
    _regionTo: BigNumberish,
    _regionFrom: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  joinGame(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  layout(
    overrides?: CallOverrides
  ): Promise<[number, number] & { rows: number; columns: number }>;

  owner(overrides?: CallOverrides): Promise<string>;

  player(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<[number, boolean] & { faction: number; joined: boolean }>;

  pleb(overrides?: CallOverrides): Promise<string>;

  regionAllowsAttack(
    _regionTo: BigNumberish,
    _regionFrom: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  regionIds(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

  regionTiers(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      workerLimit: BigNumber;
      requiredGarrison: BigNumber;
      plebPerSec: BigNumber;
    }
  >;

  regions(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      number,
      number,
      number,
      BigNumber,
      BigNumber,
      number,
      boolean,
      BigNumber,
      [number, BigNumber, BigNumber] & {
        attacker: number;
        attackedAt: BigNumber;
        soldier: BigNumber;
      }
    ] & {
      id: number;
      column: number;
      row: number;
      tier: number;
      garrison: BigNumber;
      totalWorker: BigNumber;
      controlledBy: number;
      besieged: boolean;
      cantGetAttackedTill: BigNumber;
      siege: [number, BigNumber, BigNumber] & {
        attacker: number;
        attackedAt: BigNumber;
        soldier: BigNumber;
      };
    }
  >;

  regionsPerFaction(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resolveSiege(
    _region: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDeploymentDone(
    _rows: BigNumberish,
    _columns: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRegionTiers(
    tiers: [
      {
        workerLimit: BigNumberish;
        requiredGarrison: BigNumberish;
        plebPerSec: BigNumberish;
      },
      {
        workerLimit: BigNumberish;
        requiredGarrison: BigNumberish;
        plebPerSec: BigNumberish;
      },
      {
        workerLimit: BigNumberish;
        requiredGarrison: BigNumberish;
        plebPerSec: BigNumberish;
      },
      {
        workerLimit: BigNumberish;
        requiredGarrison: BigNumberish;
        plebPerSec: BigNumberish;
      },
      {
        workerLimit: BigNumberish;
        requiredGarrison: BigNumberish;
        plebPerSec: BigNumberish;
      }
    ],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSettings(
    _ticketPrice: BigNumberish,
    _rallyTime: BigNumberish,
    _siegeTime: BigNumberish,
    _siegeCooldown: BigNumberish,
    _overwhelming: BigNumberish,
    _overwhelmingPenalty: BigNumberish,
    _plebForSoldier: BigNumberish,
    _plebForWorker: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settings(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      ticketPrice: BigNumber;
      rallyTime: BigNumber;
      siegeTime: BigNumber;
      siegeCooldown: BigNumber;
      overwhelming: BigNumber;
      overwhelmingPenalty: BigNumber;
      plebForSoldier: BigNumber;
      plebForWorker: BigNumber;
    }
  >;

  siegeOutcome(
    _region: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, boolean, BigNumber]>;

  ticketRevenueRecipient(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    attack(
      regionTo: BigNumberish,
      regionFrom: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    claimFees(overrides?: CallOverrides): Promise<void>;

    claimPleb(
      _region: BigNumberish,
      _frontendFee: BigNumberish,
      _frontendProvider: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTicketRevenue(overrides?: CallOverrides): Promise<void>;

    claimableFees(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    createRegions(
      _regionId: BigNumberish[],
      _column: BigNumberish[],
      _row: BigNumberish[],
      _neighbors: BigNumberish[][],
      _tier: BigNumberish[],
      _garrison: BigNumberish[],
      _controlledBy: BigNumberish[],
      _cantGetAttackedTill: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    deployGarrison(
      regionTo: BigNumberish,
      neighborRegion: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    deployWorker(
      regionTo: BigNumberish,
      workerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deploymentDone(overrides?: CallOverrides): Promise<boolean>;

    factionDead(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getClaimablePleb(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProductionByLord(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    getRegion(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number[],
        number,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber
      ] & {
        id_: number;
        column_: number;
        row_: number;
        neighbors_: number[];
        tier_: number;
        garrison_: BigNumber;
        totalWorker_: BigNumber;
        controlledBy_: number;
        besieged_: boolean;
        cantGetAttackedTill_: BigNumber;
      }
    >;

    getRegionIds(overrides?: CallOverrides): Promise<number[]>;

    getRegionTiers(
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber] & {
          workerLimit: BigNumber;
          requiredGarrison: BigNumber;
          plebPerSec: BigNumber;
        },
        [BigNumber, BigNumber, BigNumber] & {
          workerLimit: BigNumber;
          requiredGarrison: BigNumber;
          plebPerSec: BigNumber;
        },
        [BigNumber, BigNumber, BigNumber] & {
          workerLimit: BigNumber;
          requiredGarrison: BigNumber;
          plebPerSec: BigNumber;
        },
        [BigNumber, BigNumber, BigNumber] & {
          workerLimit: BigNumber;
          requiredGarrison: BigNumber;
          plebPerSec: BigNumber;
        },
        [BigNumber, BigNumber, BigNumber] & {
          workerLimit: BigNumber;
          requiredGarrison: BigNumber;
          plebPerSec: BigNumber;
        }
      ]
    >;

    getSiege(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber] & {
        attacker_: number;
        attackedAt_: BigNumber;
        soldier_: BigNumber;
      }
    >;

    isNeighbor(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    joinGame(overrides?: CallOverrides): Promise<void>;

    layout(
      overrides?: CallOverrides
    ): Promise<[number, number] & { rows: number; columns: number }>;

    owner(overrides?: CallOverrides): Promise<string>;

    player(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[number, boolean] & { faction: number; joined: boolean }>;

    pleb(overrides?: CallOverrides): Promise<string>;

    regionAllowsAttack(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    regionIds(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

    regionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        workerLimit: BigNumber;
        requiredGarrison: BigNumber;
        plebPerSec: BigNumber;
      }
    >;

    regions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        number,
        number,
        BigNumber,
        BigNumber,
        number,
        boolean,
        BigNumber,
        [number, BigNumber, BigNumber] & {
          attacker: number;
          attackedAt: BigNumber;
          soldier: BigNumber;
        }
      ] & {
        id: number;
        column: number;
        row: number;
        tier: number;
        garrison: BigNumber;
        totalWorker: BigNumber;
        controlledBy: number;
        besieged: boolean;
        cantGetAttackedTill: BigNumber;
        siege: [number, BigNumber, BigNumber] & {
          attacker: number;
          attackedAt: BigNumber;
          soldier: BigNumber;
        };
      }
    >;

    regionsPerFaction(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    resolveSiege(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDeploymentDone(
      _rows: BigNumberish,
      _columns: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setRegionTiers(
      tiers: [
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        }
      ],
      overrides?: CallOverrides
    ): Promise<void>;

    setSettings(
      _ticketPrice: BigNumberish,
      _rallyTime: BigNumberish,
      _siegeTime: BigNumberish,
      _siegeCooldown: BigNumberish,
      _overwhelming: BigNumberish,
      _overwhelmingPenalty: BigNumberish,
      _plebForSoldier: BigNumberish,
      _plebForWorker: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    settings(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        ticketPrice: BigNumber;
        rallyTime: BigNumber;
        siegeTime: BigNumber;
        siegeCooldown: BigNumber;
        overwhelming: BigNumber;
        overwhelmingPenalty: BigNumber;
        plebForSoldier: BigNumber;
        plebForWorker: BigNumber;
      }
    >;

    siegeOutcome(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean, BigNumber]>;

    ticketRevenueRecipient(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Attacked(address,uint8,uint8,uint256)"(
      player?: null,
      faction?: null,
      region?: null,
      soldier?: null
    ): TypedEventFilter<
      [string, number, number, BigNumber],
      { player: string; faction: number; region: number; soldier: BigNumber }
    >;

    Attacked(
      player?: null,
      faction?: null,
      region?: null,
      soldier?: null
    ): TypedEventFilter<
      [string, number, number, BigNumber],
      { player: string; faction: number; region: number; soldier: BigNumber }
    >;

    "ClaimedPleb(address,uint256)"(
      player?: null,
      pleb?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { player: string; pleb: BigNumber }
    >;

    ClaimedPleb(
      player?: null,
      pleb?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { player: string; pleb: BigNumber }
    >;

    "DeployedGarrison(address,uint8,uint256)"(
      player?: null,
      region?: null,
      soldier?: null
    ): TypedEventFilter<
      [string, number, BigNumber],
      { player: string; region: number; soldier: BigNumber }
    >;

    DeployedGarrison(
      player?: null,
      region?: null,
      soldier?: null
    ): TypedEventFilter<
      [string, number, BigNumber],
      { player: string; region: number; soldier: BigNumber }
    >;

    "DeployedWorker(address,uint8,uint256)"(
      player?: null,
      region?: null,
      worker?: null
    ): TypedEventFilter<
      [string, number, BigNumber],
      { player: string; region: number; worker: BigNumber }
    >;

    DeployedWorker(
      player?: null,
      region?: null,
      worker?: null
    ): TypedEventFilter<
      [string, number, BigNumber],
      { player: string; region: number; worker: BigNumber }
    >;

    "DeploymentDone()"(): TypedEventFilter<[], {}>;

    DeploymentDone(): TypedEventFilter<[], {}>;

    "FactionLost(uint8)"(
      faction?: null
    ): TypedEventFilter<[number], { faction: number }>;

    FactionLost(
      faction?: null
    ): TypedEventFilter<[number], { faction: number }>;

    "FeesClaimed(address,uint256)"(
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { account: string; amount: BigNumber }
    >;

    FeesClaimed(
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { account: string; amount: BigNumber }
    >;

    "JoinedGame(address,uint8)"(
      player?: null,
      faction?: null
    ): TypedEventFilter<[string, number], { player: string; faction: number }>;

    JoinedGame(
      player?: null,
      faction?: null
    ): TypedEventFilter<[string, number], { player: string; faction: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "RegionTierIncreased(uint8,uint8)"(
      region?: null,
      tier?: null
    ): TypedEventFilter<[number, number], { region: number; tier: number }>;

    RegionTierIncreased(
      region?: null,
      tier?: null
    ): TypedEventFilter<[number, number], { region: number; tier: number }>;

    "ResolvedSiege(uint8,uint8,uint256,uint8,uint256,bool)"(
      region?: null,
      defender?: null,
      defendingSoldier?: null,
      attacker?: null,
      attackingSoldier?: null,
      defenderWon?: null
    ): TypedEventFilter<
      [number, number, BigNumber, number, BigNumber, boolean],
      {
        region: number;
        defender: number;
        defendingSoldier: BigNumber;
        attacker: number;
        attackingSoldier: BigNumber;
        defenderWon: boolean;
      }
    >;

    ResolvedSiege(
      region?: null,
      defender?: null,
      defendingSoldier?: null,
      attacker?: null,
      attackingSoldier?: null,
      defenderWon?: null
    ): TypedEventFilter<
      [number, number, BigNumber, number, BigNumber, boolean],
      {
        region: number;
        defender: number;
        defendingSoldier: BigNumber;
        attacker: number;
        attackingSoldier: BigNumber;
        defenderWon: boolean;
      }
    >;

    "SettingsChanged(tuple,tuple)"(
      oldSettings?: null,
      newSettings?: null
    ): TypedEventFilter<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        }
      ],
      {
        oldSettings: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        };
        newSettings: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        };
      }
    >;

    SettingsChanged(
      oldSettings?: null,
      newSettings?: null
    ): TypedEventFilter<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        }
      ],
      {
        oldSettings: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        };
        newSettings: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          ticketPrice: BigNumber;
          rallyTime: BigNumber;
          siegeTime: BigNumber;
          siegeCooldown: BigNumber;
          overwhelming: BigNumber;
          overwhelmingPenalty: BigNumber;
          plebForSoldier: BigNumber;
          plebForWorker: BigNumber;
        };
      }
    >;
  };

  estimateGas: {
    attack(
      regionTo: BigNumberish,
      regionFrom: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimFees(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimPleb(
      _region: BigNumberish,
      _frontendFee: BigNumberish,
      _frontendProvider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTicketRevenue(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimableFees(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    createRegions(
      _regionId: BigNumberish[],
      _column: BigNumberish[],
      _row: BigNumberish[],
      _neighbors: BigNumberish[][],
      _tier: BigNumberish[],
      _garrison: BigNumberish[],
      _controlledBy: BigNumberish[],
      _cantGetAttackedTill: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployGarrison(
      regionTo: BigNumberish,
      neighborRegion: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployWorker(
      regionTo: BigNumberish,
      workerAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deploymentDone(overrides?: CallOverrides): Promise<BigNumber>;

    factionDead(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaimablePleb(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProductionByLord(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRegion(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRegionIds(overrides?: CallOverrides): Promise<BigNumber>;

    getRegionTiers(overrides?: CallOverrides): Promise<BigNumber>;

    getSiege(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isNeighbor(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    joinGame(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    layout(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    player(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    pleb(overrides?: CallOverrides): Promise<BigNumber>;

    regionAllowsAttack(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    regionIds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    regionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    regions(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    regionsPerFaction(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resolveSiege(
      _region: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDeploymentDone(
      _rows: BigNumberish,
      _columns: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRegionTiers(
      tiers: [
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        }
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSettings(
      _ticketPrice: BigNumberish,
      _rallyTime: BigNumberish,
      _siegeTime: BigNumberish,
      _siegeCooldown: BigNumberish,
      _overwhelming: BigNumberish,
      _overwhelmingPenalty: BigNumberish,
      _plebForSoldier: BigNumberish,
      _plebForWorker: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settings(overrides?: CallOverrides): Promise<BigNumber>;

    siegeOutcome(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ticketRevenueRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    attack(
      regionTo: BigNumberish,
      regionFrom: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimFees(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimPleb(
      _region: BigNumberish,
      _frontendFee: BigNumberish,
      _frontendProvider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTicketRevenue(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimableFees(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createRegions(
      _regionId: BigNumberish[],
      _column: BigNumberish[],
      _row: BigNumberish[],
      _neighbors: BigNumberish[][],
      _tier: BigNumberish[],
      _garrison: BigNumberish[],
      _controlledBy: BigNumberish[],
      _cantGetAttackedTill: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployGarrison(
      regionTo: BigNumberish,
      neighborRegion: BigNumberish,
      soldierAmount: BigNumberish,
      resolvesSiege: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployWorker(
      regionTo: BigNumberish,
      workerAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deploymentDone(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factionDead(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaimablePleb(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProductionByLord(
      _region: BigNumberish,
      _player: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRegion(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRegionIds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRegionTiers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSiege(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isNeighbor(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    joinGame(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    layout(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    player(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pleb(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    regionAllowsAttack(
      _regionTo: BigNumberish,
      _regionFrom: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    regionIds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    regionTiers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    regions(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    regionsPerFaction(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resolveSiege(
      _region: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDeploymentDone(
      _rows: BigNumberish,
      _columns: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRegionTiers(
      tiers: [
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        },
        {
          workerLimit: BigNumberish;
          requiredGarrison: BigNumberish;
          plebPerSec: BigNumberish;
        }
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSettings(
      _ticketPrice: BigNumberish,
      _rallyTime: BigNumberish,
      _siegeTime: BigNumberish,
      _siegeCooldown: BigNumberish,
      _overwhelming: BigNumberish,
      _overwhelmingPenalty: BigNumberish,
      _plebForSoldier: BigNumberish,
      _plebForWorker: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settings(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    siegeOutcome(
      _region: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ticketRevenueRecipient(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
